[package]
name = "onefig"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flexar = "0.3.11"
clap = { version = "4.4.6", features = ["derive"] }

[profile.dev.package."*"]
opt-level = 3